### ISSUE TITLE
Error with GHC 7.10

### ISSUE THREAD

**Issue by HMPerson1** [bennofs/dynamic-cabal#9] opened 2015-03-29 03:58 UTC
Travis log: https://travis-ci.org/bennofs/dynamic-cabal/jobs/56236526#L581
```
[1 of 4] Compiling Distribution.Client.Dynamic.Query ( src/Distribution/Client/Dynamic/Query.hs, dist/build/Distribution/Client/Dynamic/Query.o )
src/Distribution/Client/Dynamic/Query.hs:189:36:
    Couldn't match expected type ‘DynFlags.PackageFlag’
                with actual type ‘DynFlags.ModRenaming -> DynFlags.PackageFlag’
    In the expression:
      DynFlags.ExposePackage $ "Cabal-" ++ showVersion version
    In the ‘GHC.packageFlags’ field of a record
    In the second argument of ‘($)’, namely
      ‘dflags
         {GHC.ghcLink = GHC.LinkInMemory,
          GHC.hscTarget = GHC.HscInterpreted,
          GHC.packageFlags = [DynFlags.ExposePackage
                              $ "Cabal-" ++ showVersion version],
          GHC.ctxtStkDepth = 1000}’
src/Distribution/Client/Dynamic/Query.hs:189:61:
    Couldn't match expected type ‘DynFlags.PackageArg’
                with actual type ‘[Char]’
    In the second argument of ‘($)’, namely
      ‘"Cabal-" ++ showVersion version’
    In the expression:
      DynFlags.ExposePackage $ "Cabal-" ++ showVersion version
    In the ‘GHC.packageFlags’ field of a record
```

**Comment by bennofs** [comment] 2015-03-29 14:34
I'm currently working on this. The build should be fixed now, I'll release a new version very soon.

**Comment by bennofs** [comment] 2015-03-29 14:35
Duplicate of #8.

**Closed by bennofs** 2015-03-29 14:35 UTC
